<style>
  body {
    background-color: #F0F7FF;
  }
  .about-section {
    margin-top: 100px;
    margin-bottom: 100px; 
    padding: 50px;
  }
  .about-section h1 {
    color: #0077B6;
  }
  p {
    color: #444444;
  }
</style>
<div class="about-section">
  <h1>À propos d'Equilib</h1>
    <p>Chez Equilib, nous sommes une équipe de passionnés de chevaux et de professionnels de la santé équine qui 
      ont pour mission de faciliter la vie des propriétaires de chevaux et des vétérinaires en réinventant la prise 
      de rendez-vous en ligne et la gestion de la relation client.
    </p>
    <p>Notre plateforme permet aux propriétaires de chevaux de trouver facilement un vétérinaire équin qualifié et 
      disponible pour prendre soin de leur animal. Nous avons créé une solution simple, rapide et efficace pour la 
      prise de rendez-vous en ligne, ainsi qu'une véritable solution de communication vétérinaire-client numérique 
      pour améliorer la relation entre les propriétaires de chevaux et les vétérinaires équins.
    </p>
    <p>Pour les vétérinaires équins, Equilib offre une solution de gestion de rendez-vous en ligne facile à utiliser, 
      qui leur permet de rester en contact avec leurs clients, même entre les rendez-vous. Notre plateforme propose également 
      des fonctionnalités inédites, comme la messagerie instantanée, la gestion multi-sites et la possibilité de partager des 
      fichiers avec les clients pour faciliter la communication.
    </p>
    <p>Nous sommes convaincus qu'Equilib est la solution idéale pour simplifier la vie des propriétaires de chevaux et des 
      vétérinaires équins. Nous sommes fiers de fournir un service de qualité pour améliorer la santé et le bien-être des 
      chevaux et de leurs propriétaires.
    </p>
</div>