
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>

<div class="p-0 m-0 border-0 bd-example bg-body-secondary faq">
  <h1 style="text-align:center">FAQ</h1>
    <div class="accordion accordion-flush" id="accordionFlushExample">
      <div class="accordion-item">
        <h2 class="accordion-header" id="flush-headingOne">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
            <strong>Qu'est ce que Equilib ?</strong> 
          </button>
        </h2>

        <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample" >
          <div class="accordion-body">
        <strong> Vous êtes propriétaire d’un animal ? </strong> <br>
        <p>Equilib vous permet de trouver en un instant le vétérinaire le plus disponible et le plus proche de chez vous. <br>
           Vous pouvez dès maintenant prendre rendez-vous directement en ligne, 24h/24 et 7j/7 en quelques secondes !
        </p>

        <strong>Vous êtes vétérinaire ?</strong> <br>
        Equilib est là pour vous aider ! <br>
        <p>Equilib a développé un service complet dédié à la profession vétérinaire qui permet simultanément d’attirer de nouveaux clients, <br> 
           réduire les rendez-vous non honorés et de gagner du temps à la faveur d’une solution complète de gestion de vos rendez-vous et du développement de votre clientèle.
         </p>
    </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header" id="flush-headingTwo">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
           <strong>Equilib respecte t-il la confidentialité de mes données personnelles ?</strong> 
          </button>
        </h2>
        <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample" >
          <div class="accordion-body">
        <p>
            Tout est mis en oeuvre pour sécuriser toutes les informations lors de vos connections. <br>
            C’est l’une de nos priorités : Nous prenons très au sérieux la confidentialité de nos clients et des utilisateurs de Equilib. <br>
            A aucun moment, nous ne transmettrons vos données personnelles à des tiers.
        </p>
</div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header" id="flush-headingThree">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
          <strong>Est-ce que le service Equilib est gratuit pour les propriétaires d’animaux ?</strong>
          </button>
        </h2>
        <div id="flush-collapseThree" class="accordion-collapse collapse" aria-labelledby="flush-headingThree" data-bs-parent="#accordionFlushExample">
          <div class="accordion-body">
            <p>
                Absolument ! Vous pouvez prendre rendez-vous gratuitement sur le site.
            </p>
        </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header" id="flush-headingFour">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseFour" aria-expanded="false" aria-controls="flush-collapseFour">
          <strong>Je suis Vétérinaire : Comment m’inscrire ?</strong>
          </button>
        </h2>
        <div id="flush-collapseFour" class="accordion-collapse collapse" aria-labelledby="flush-headingFour" data-bs-parent="#accordionFlushExample">
          <div class="accordion-body">
            <p>
                Rien de plus simple : Il vous suffit de <a href="signupPro.php"> cliquer ici </a> ! <br>
             Pour vous inscrire, renseignez simplement les informations demandées, puis cliquez sur "S’inscrire maintenant".
            </p>
        </div>
        </div>
      </div>

      <div class="accordion-item">
        <h2 class="accordion-header" id="flush-headingFive">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseFive" aria-expanded="false" aria-controls="flush-collapseFive">
          <strong>Comment prendre un rendez-vous avec Equilib ?</strong>
          </button>
        </h2>
        <div id="flush-collapseFive" class="accordion-collapse collapse" aria-labelledby="flush-headingFive" data-bs-parent="#accordionFlushExample">
          <div class="accordion-body">
            <p>
                Rien de plus facile ! <br>
                Vous devez tout simplement suivre ces 3 étapes : <br>
                Rechercher un vétérinaire soit en saisissant la localité, le nom de votre vétérinaire ou l’établissement soit par la spécialité. <br>
                Choisissez le vétérinaire puis cliquez sur l'horaire qui vous convient. <br>
                Renseignez le ou les noms de vos animaux ainsi que le motif de consultation puis cliquez sur "valider la demande de rendez-vous". <br>
                Votre rendez-vous est maintenant pris ! <br>
                Un email de confirmation vous sera alors envoyé ainsi qu’un SMS de rappel la veille du rendez-vous. <br>
            </p>
            </div>
        </div>
      </div>

      <div class="accordion-item">
        <h2 class="accordion-header" id="flush-headingSix">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseSix" aria-expanded="false" aria-controls="flush-collapseSix">
          <strong>Comment accéder à l’historique de mes rendez-vous ?</strong>
          </button>
        </h2>
        <div id="flush-collapseSix" class="accordion-collapse collapse" aria-labelledby="flush-headingSix" data-bs-parent="#accordionFlushExample">
          <div class="accordion-body">
            <p>
            Connectez-vous à votre compte sur equilib.fr en cliquant sur "connexion" ou sur votre nom si vous êtes déjà connecté. <br>
            Accédez à la rubrique "Mes rendez-vous".
            </p>
            </div>
        </div>
      </div>

      <div class="accordion-item">
        <h2 class="accordion-header" id="flush-headingSeven">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseSeven" aria-expanded="false" aria-controls="flush-collapseSeven">
          <strong>Comment modifier mes informations personnelles ?</strong>
          </button>
        </h2>
        <div id="flush-collapseSeven" class="accordion-collapse collapse" aria-labelledby="flush-headingSeven" data-bs-parent="#accordionFlushExample">
          <div class="accordion-body">
            <p>
                Pour apporter des modifications sur votre compte ou en ajouter : <br>
                Connectez-vous à votre compte sur equilib.fr en cliquant sur “connexion” ou sur votre nom si vous êtes déjà connecté. <br>
                Accédez à la rubrique "Mon profil".<br>
                Les éléments suivant peuvent être modifiés :<br>
                Votre ou vos animaux.<br>
                Votre adresse e-mail.<br>
                Votre mot de passe.<br>
                Votre date de naissance.<br>
                Votre adresse postale.<br>
                Votre numéro de téléphone.<br>
                Lorsqu'un ou plusieurs éléments ont été modifiés ou ajoutés, cliquez sur "Enregistrer".
            </p>
            </div>
        </div>
      </div>

      <div class="accordion-item">
        <h2 class="accordion-header" id="flush-headingEight">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseEight" aria-expanded="false" aria-controls="flush-collapseEight">
          <strong>Comment annuler un rendez-vous ?</strong>
          </button>
        </h2>
        <div id="flush-collapseEight" class="accordion-collapse collapse" aria-labelledby="flush-headingEight" data-bs-parent="#accordionFlushExample">
          <div class="accordion-body">
            <p>
                Vous pouvez annuler un rendez-vous jusqu’à 4h avant l’horaire prévue. Passé ce délai, il vous faut contacter le vétérinaire par téléphone pour annuler le rendez-vous. <br>
                Connectez-vous à votre compte sur equilib.fr en cliquant sur "connexion" ou sur votre nom si vous êtes déjà connecté. <br>
                Accédez à la rubrique "Mes rendez-vous" et cliquez en face du rendez-vous concerné sur le bouton "Annuler ce rendez-vous".<br>
                Votre rendez-vous est annulé et la mention "annulé" apparaîtra en face du rendez-vous concerné dans l'historique "Mes rendez-vous".
            </p>
          </div>
        </div>
      </div>

      <div class="accordion-item">
        <h2 class="accordion-header" id="flush-headingNine">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseNine" aria-expanded="false" aria-controls="flush-collapseNine">
          <strong> J'ai oublié mon mot de passe. Comment le réinitialiser ?</strong>
          </button>
        </h2>
        <div id="flush-collapseNine" class="accordion-collapse collapse" aria-labelledby="flush-headingNine" data-bs-parent="#accordionFlushExample">
          <div class="accordion-body">
            <p>
                Si vous avez oublié votre mot de passe, vous pouvez le réinitialiser en suivant les étapes suivantes : <br>
<!-- AJOUTER LIEN PASSWORD  ---------------------------------------->
                Accèdez à la page "Reinitialiser mon mot de passe" en <a href="">cliquant ici</a>. <br>
                Saisissez votre adresse e-mail et cliquez sur "Envoyer". <br>
                Un email avec un mot de passe provisoire vous sera transmis. <br>
                Vous pourrez ensuite modifier le mot de passe en Accédez à la rubrique "Mon profil" puis "modifier mon mot de passe".
            </p>
          </div>
        </div>
      </div>

      <div class="accordion-item">
        <h2 class="accordion-header" id="flush-headingTen">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTen" aria-expanded="false" aria-controls="flush-collapseTen">
          <strong> Une question particulière ?</strong>
          </button>
        </h2>
        <div id="flush-collapseTen" class="accordion-collapse collapse" aria-labelledby="flush-headingTen" data-bs-parent="#accordionFlushExample">
          <div class="accordion-body">
<!-- AJOUTER LIEN POUR FORMULAIRE DE CONTACT @EQUILLIB -->
            <p>
                Vous pouvez nous contacter en <a href="">cliquant ici</a>.
            </p>
          </div>
        </div>
      </div>
    </div>
    </div>