<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.2.0/sweetalert2.min.css">

<div class="appointment">
<div class="appointmentsection">
<div class="professional-infos">
    <h1>Vous souhaitez prendre rend-vous avec :</h1>
    <h2>Dr <?=$pro->getFirstname(), ' ', $pro->getLastname();?></h2>
    <p><?=$pro->getSpeciality()->getName()?></p>
    <p><?=$pro->getPostalCode();?> <br>
    <p><?=$pro->getCity();?> <br>
    <?=$pro->getAddress();?></p>
    <p>Tèl : <?= $pro->getPhoneNumber(); ?></p>
</div>

<div class="appointment-form">
    <h3>Prendre rendez-vous</h3>
    <form method="POST" data-redirect= "<?= constructUrl('home') ?>" action="<?= constructUrl('appointmentPatient', ['id' => $pro->getId_professionnal()]); ?>" id="myForm">
            <div class="form-group row mb-3">
                <label for="date" class="col-sm-2 col-form-label">Date:</label>
                <div class="col-sm-5">
                    <input type="date" class="form-control" name="date" id="date" value="<?= $date ?>">
                </div>
            </div>
            <div class="form-group row mb-3">
    <label for="hours" class="col-sm-2 col-form-label">Heure:</label>
    <div class="col-sm-5">
        <select class="form-select" name="hours" id="hours">
            <?php echo $this->generateTimeOptions($hours); ?>
        </select>
    </div>
</div>

    <div class="form-group row mb-3">                
        <label for="horse">Pour quel cheval souhaitez vous prendre rendez-vous?</label>
                <select class="form-control" id="horse_id" name="horse">
                <option value="-1">Selectionner le cheval</option>
                    <?php foreach ($horses as $horse): ?>
                        <option value="<?= $horse->getId_horse(); ?>"><?= $horse->getName(); ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            
            <div class="form-group row mb-3">
                <label for="message" class="col-sm-2 col-form-label">Message:</label>
                <div class="col-sm-5">
                    <textarea class="form-control" name="message" id="message" ><?= $message ?></textarea>
                </div>
            </div>

            <div class="form-group row mb-3">
                <div class="col-sm-5"></div>
                <div class="col-sm-10">
                <input type="submit" class="btn btn-primary" name="submit" value="Prendre rendez-vous" id="success">
                </div>
            </div>
        </form>   
</div>
</div>
<img src="<?=asset('assets/appointment.png');?>" alt="apppointment">
</div>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.2.0/sweetalert2.all.min.js"></script>

<script>
 document.getElementById('myForm').addEventListener('submit', function(e) {
    e.preventDefault();

    var form = document.getElementById('myForm');
    var formData = new FormData(form);

    fetch(form.action, {
        method: 'POST',
        body: formData
    })
    .then(response => response.json())
    .then(data => {
        console.log(data);
        if (data.success) {
            Swal.fire({
                title: 'Bravo',
                html: 'Votre rendez-vous a été pris avec <b style="color:green;">succès</b>!',
                icon: 'success',
                confirmButtonText: 'OK'
            }).then((result) => {
                if (result.isConfirmed) {
                    window.location.href = form.dataset.redirect;
                }
            });
        } else {
            Swal.fire({
                title: 'Erreur',
                text: 'Veuillez remplir tous les champs',
                icon: 'error',
                confirmButtonText: 'OK'
            }).then((result) => {
                if (result.isConfirmed) {
                    for (const fieldName in data.errors) {
                    const p = document.createElement('p');
                    p.textContent = data.errors[fieldName];
                    p.className ='alert alert-danger';
                    const input = document.getElementById(fieldName);
                    input.after(p);
                    }
                }
            })
        }
    })
    .catch(error => {
        Swal.fire({
            title: 'Erreur',
            text: 'Une erreur s\'est produite lors de l\'enregistrement du formulaire.',
            icon: 'error',
            confirmButtonText: 'OK'
        });
        console.error('Erreur :', error);
    });
});

</script>

<!-- <script>    
$(document).on('click', '#success', function(e) {
  e.preventDefault(); // Empêche la soumission du formulaire

  var date = $('#date').val();
  var hours = $('#hours').val();
  var horse = $('#horse').val();
  var message = $('#message').val();

  // Vérification des champs obligatoires
  if (!date || !hours || !horse || !message) {
    Swal.fire({
      title: 'Erreur',
      text: 'Veuillez remplir tous les champs.',
      icon: 'error',
      confirmButtonText: 'OK'
    });
    return;
  }

  Swal.fire({
    title: 'Bravo',
    html: 'Votre rendez-vous a été pris avec <b style="color:green;">succès</b>!',
    icon: 'success',
    confirmButtonText: 'OK'
  }).then((result) => {
    if (result.isConfirmed) {
      // Redirection vers la page d'accueil
      window.location.href = '<?= constructUrl('home') ?>';
    }
  });
});
</script> -->





