<?php
    // Vérifiez si $_SESSION['error_message'] existe
    if (isset($_SESSION['error_message'])) {
        // Affichez le message d'erreur et détruisez la variable $_SESSION['error_message']
        echo "<p style='color: red'>" . $_SESSION['error_message'] . "</p>";
        unset($_SESSION['error_message']);
    }
    ?>

<div class="create-account">
  <img src="<?=asset('assets/signup.png');?>" alt="signup">
    <div class="d-flex justify-content-center align-items-center border p-4 my-5">
      <form action="<?=constructUrl('signupPatient');?>" method="post" class="form-patient">
        <h1>Création de compte patient</h1>
          <div class="form-group">
            <label for="lastname">Nom :</label>
            <input type="text" class="form-control" id="lastname" name="lastname" value="<?=$lastname;?>">
            <?php if(isset($errors['lastname'])): ?>
              <p class="error text-danger"><?=$errors['lastname'];?></p>
            <?php endif; ?>

          </div>
          <div class="form-group">
            <label for="firstname">Prénom :</label>
            <input type="text" class="form-control" id="firstname" name="firstname" value="<?=$firstname;?>">
            <?php if(isset($errors['firstname'])): ?>
              <p class="error text-danger"><?=$errors['firstname'];?></p>
            <?php endif; ?>
          </div>

          <div class="form-group">
            <label for="email">Email :</label>
            <input type="text" class="form-control" id="email" name="email" value="<?=$email;?>">
            <?php if(isset($errors['email'])): ?>
              <p class="error text-danger"><?=$errors['email'];?></p>
            <?php endif; ?>
          </div>

          <div class="form-group">
            <label for="address">Adresse :</label>
            <input type="text" class="form-control" id="address" name="address" value="<?=$address;?>">
            <?php if(isset($errors['address'])): ?>
              <p class="error text-danger"><?=$errors['address'];?></p>
            <?php endif; ?>
          </div>

          <div class="form-group">
            <label for="phoneNumber">Téléphone :</label>
            <input type="tel" class="form-control" id="phoneNumber" name="phoneNumber" value="<?=$phoneNumber;?>">
            <?php if(isset($errors['phoneNumber'])): ?>
              <p class="error text-danger"><?=$errors['phoneNumber'];?></p>
            <?php endif; ?>
          </div>

          <div class="form-group">
            <label for="password">Mot de passe :</label>
            <input type="password" class="form-control" id="password" name="password">
            <?php if(isset($errors['password'])): ?>
              <p class="error text-danger"><?=$errors['password'];?></p>
            <?php endif; ?>
          </div>

          <div class="form-group">
            <label for="password-confirm">Confirmation :</label>
            <input type="password" class="form-control" id="password-confirm" name="password-confirm">
            <?php if(isset($errors['password-confirm'])): ?>
              <p class="error text-danger"><?=$errors['password-confirm'];?></p>
            <?php endif; ?>
          </div>
          
          <button type="submit" class="btn btn-primary">Créer compte</button>
      </form>
  </div>
</div>