<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
        <!-- CSS de Bootstrap -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <!-- JavaScript de jQuery (requis pour Bootstrap) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- JavaScript de Bootstrap -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="<?=asset('css/indexPro.css');?>" />
    <link rel="stylesheet" href="<?=asset('css/style.css');?>" />
    <link rel="stylesheet" href="<?=asset('css/index.css');?>" />
    <link rel="stylesheet" href="<?=asset('css/signup.css');?>" />
    <link rel="stylesheet" href="<?=asset('css/base.css');?>" />
</head>
<body>
    <header>
    
    <nav class="navbar navbar-expand-lg bg-body-tertiary navbar-custom">
        <img src="<?=asset('assets/logo-equilib.png');?>" alt="logo" width="50px">
          <div class="container-fluid">
            <a class="navbar-brand" href="<?=constructUrl('homeAdmin');?>">Admin</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <?php if(!(new App\Services\AdminSession)->getAdmin()): ?>
                <li class="nav-item">
                  <a class="nav-link" href="<?=constructUrl('loginAdmin');?>">Connexion</a>
                </li>
                <?php else: ?>
                <li class="nav-item">
                  <a class="nav-link" href=""> 
                    <?php if((new App\Services\AdminSession)->getAdmin()): ?>
                  <?php endif ?></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="<?=constructUrl('specialityAdmin');?>">Spécialités</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="<?=constructUrl('patientList');?>">Patients</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="<?=constructUrl('proList');?>">Vétérinaires</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="<?=constructUrl('logoutAdmin');?>">Déconnexion</a>
                </li>
                <?php endif; ?>
              </ul>
            </div>
          </div>
    </nav>
  </header>

    <main>

    <?php if (isset($flashMessage) && $flashMessage):?>
          <div class="alert alert-success"><?php echo $flashMessage;?></div> 
        <?php endif;?>
        
      <!-- Contenu de la page -->
      <?php include TEMPLATE_DIR . '/admin/' . $template . '.phtml'; ?>
    </main>


<script src="<?=asset('js/script.js');?>"></script>
<script src="<?=asset('js/vicopo-vanilla.min.js');?>"></script>
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script>
    AOS.init();
  </script>

</body>
</html>