<h1>Liste des patients</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Prénom</th>
      <th scope="col">Nom</th>
      <th scope="col">Email</th>
      <th scope="col">Adresse</th>
      <th scope="col">Numéro de téléphone</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($patients as $patient): ?>
      <tr>
        <th><?=$patient->getId_patient()?></th>
        <td><?=$patient->getFirstname()?></td>
        <td><?=$patient->getLastname()?></td>
        <td><?=$patient->getEmail()?></td>
        <td><?=$patient->getAddress()?></td>
        <td><?=$patient->getPhoneNumber()?></td>
      </tr>
    <?php endforeach; ?>
  </tbody>
</table>
