<h1>Liste des spécialités</h1>

<form method="post" action="<?= constructUrl('createSpeciality'); ?>">
    <label for="name">Nom de la spécialité :</label>
    <input type="text" id="name" name="name" required>
    <button type="submit" class="btn btn-success">Ajouter</button>
</form>


<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nom</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($specialities as $speciality): ?>
            <tr>
                <td><?= $speciality['id']; ?></td>
                <td id='speciality-<?= $speciality['id']?>'><?php echo $speciality['name']; ?></td>
                <td>
                    <!-- Bouton Modifier avec identifiant unique -->
                    <button data-id="<?php echo $speciality['id']; ?>" data-name="<?php echo $speciality['name']; ?>" class="btn btn-primary updateButton">Modifier</button>
                    <!-- Autres actions -->
                    <a href="<?= constructUrl('deleteSpeciality', ['id' => $speciality['id']]); ?>" class="btn btn-danger">Supprimer</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

        <!-- Div cachée contenant le formulaire de mise à jour de la spécialité -->
<div id="editSpecialityModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="editSpecialityModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editSpecialityModalLabel">Modifier la spécialité</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fermer">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form data-url="<?= constructUrl('updateSpecialityAjax'); ?>" method="post" id='updateSpecialityForm' action="<?= constructUrl('updateSpeciality'); ?>">
                    <input type="hidden" name="id-speciality">
                    <label for="name">Nom de la spécialité :</label>
                    <input type="text" id="name-speciality" name="name-speciality" required>
                    <button type="submit" class="btn btn-success">Enregistrer</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
            $('.updateButton').click(function() {
                $('#editSpecialityModal').modal('show');
                $('[name=id-speciality]').val(this.dataset.id);
                $('#name-speciality').val(this.dataset.name);
                console.log($('#name-speciailty'));
            });
    });
</script>
<script src="<?=asset("js/admin.js")?>"></script>
